### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by F0bes** [ZirconiumX/biostation#3]
Currently got it to build a bios file that pcsx2 recognizes. From my understanding the bios is supposed to execute the pillbox executable but I am only getting a black screen. Is your pillbox executable PAL or NTSC?

**Comment by Ravenslofty** [comment]
I think it's NTSC, but that doesn't matter as far as the emulator is concerned; the executable sets the right settings.

Truthfully, it's been a long time since I last touched this, and I can't quite remember how it worked, but it did work at one point.
